# Generated by Django 3.2.4 on 2021-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now=True)),
                ('booking_time', models.DateTimeField()),
            ],
            options={
                'ordering': ('booking_date',),
            },
        ),
    ]
