# Generated by Django 3.2.4 on 2021-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
